SELECT *
FROM DIM p
JOIN rules r ON 1=1
WHERE 1=1
  AND CASE
        WHEN r.ATC4_OPERATOR IS NULL OR TRIM(r.ATC4_OPERATOR) = '' THEN NULL
        WHEN r.ATC4_OPERATOR = '='  THEN UPPER(p.ATC4) = UPPER(r.ATC4)
        WHEN r.ATC4_OPERATOR = '<>' THEN UPPER(p.ATC4) <> UPPER(r.ATC4)
        WHEN r.ATC4_OPERATOR = 'LIKE' THEN UPPER(p.ATC4) LIKE '%' || UPPER(r.ATC4) || '%'
        WHEN r.ATC4_OPERATOR = 'NOT LIKE' THEN UPPER(p.ATC4) NOT LIKE '%' || UPPER(r.ATC4) || '%'
        WHEN r.ATC4_OPERATOR = 'START WITH' THEN UPPER(p.ATC4) LIKE UPPER(r.ATC4) || '%'
        WHEN r.ATC4_OPERATOR = 'END WITH' THEN UPPER(p.ATC4) LIKE '%' || UPPER(r.ATC4)
      END
